#version: '3'

services:
  fivem:
    image: spritsail/fivem
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "./resources:/config/resources"
      - "./server.cfg:/config/server.cfg"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    environment:
      CONFIG_ARGS: "+set gamename rdr3"
