#version: '3'

services:
  fivem:
# Use an image from dockerhub or uncomment and comment image to use local build. Dont forget to rebuild / pull latest if you do not use a image with fivem & docker build number.  
    image: 'skyraptor/fivem:6104-0'
#    build:
#      context: ./docker/fivem
#      args:
#        FIVEM_NUM: ${FIVEM_NUM}
#        FIVEM_VER: ${FIVEM_VER}
#        DATA_VER: ${DATA_VER}
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - 'mysql'
    volumes:
      - './resources:/config/resources'
      - '/cfg:/root/cfg'
#      - './server.cfg:/root/server.cfg' Use this for your own cfg template
    networks:
      - fivem
    ports:
      - '${BIND_IP:-0.0.0.0}:30120:30120'
      - '${BIND_IP:-0.0.0.0}:30120:30120/udp'
    environment:
      CONFIG_ARGS: '+set gamename ${GAME_NAME} +set sv_enforceGameBuild 1436 +sets sv_projectName "${SERVER_NAME}" +sets sv_projectDesc "${SERVER_DESC}"'
      LICENSE_KEY: ${LICENSE_KEY}
      NO_LICENSE_KEY: ${NO_LICENSE_KEY}
      NO_ONESYNC: ${NO_ONESYNC}
      RCON_PASSWORD: ${RCON_PASSWORD}
      STEAM_API_KEY: ${STEAM_API_KEY}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  mysql:
# Use the offical mysql image or use local build as above
    image: 'mysql:8.0'
#    build:
#      context: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './.mysql:/var/lib/mysql'
      - './sql:/docker-entrypoint-initdb.d'
    networks:
      - fivem
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      
networks:
    fivem:
        driver: bridge
