#version: '3'

services:
  fivem:
    build:
      context: ./docker
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "./resources:/config/resources"
      - "./server.cfg:/root/server.cfg"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    env_file:
    - ./.env
    environment:
      CONFIG_ARGS: "+set gamename rdr3"
