#version: '3'

services:
  fivem:
    build:
      context: ./docker
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - 'mysql'
    volumes:
      - './resources:/config/resources'
      - './server.cfg:/root/server.cfg'
    networks:
      - fivem
    ports:
      - '30120:30120'
      - '30120:30120/udp'
    environment:
      CONFIG_ARGS: '+set gamename rdr3'
      LICENSE_KEY: ${LICENSE_KEY}
      NO_LICENSE_KEY: ${NO_LICENSE_KEY}
      RCON_PASSWORD: ${RCON_PASSWORD}
      STEAM_API_KEY: ${STEAM_API_KEY}
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'redemrp'
      MYSQL_DATABASE: 'redemrp'
      MYSQL_USER: 'redemrp'
      MYSQL_PASSWORD: 'redemrp'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './mysql:/var/lib/mysql'
      - './sql:/docker-entrypoint-initdb.d'
    networks:
      - fivem
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      
networks:
    fivem:
        driver: bridge
