#version: '3'

services:
  fivem:
    build:
      context: ./docker
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "./resources:/config/resources"
      - "./server.cfg:/root/server.cfg"
    networks:
      - fivem
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    environment:
      CONFIG_ARGS: "+set gamename rdr3"
      LICENSE_KEY: ${LICENSE_KEY}
      NO_LICENSE_KEY: ${NO_LICENSE_KEY}
      RCON_PASSWORD: ${RCON_PASSWORD}
      STEAM_API_KEY: ${STEAM_API_KEY}
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'fivem'
      MYSQL_DATABASE: 'fivem'
      MYSQL_USER: 'fivem'
      MYSQL_PASSWORD: 'fivem'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './mysql:/var/lib/mysql'
    networks:
      - fivem
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      
networks:
    fivem:
        driver: bridge
