#version: '3'

services:
  fivem:
    build:
      context: ./docker
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - 'mysql'
    volumes:
      - './resources:/config/resources'
      - '/cfg:/root/cfg'
#      - './server.cfg:/root/server.cfg'
    networks:
      - fivem
    ports:
      - '${BIND_IP:-0.0.0.0}:30120:30120'
      - '${BIND_IP:-0.0.0.0}:30120:30120/udp'
    environment:
      CONFIG_ARGS: '+set gamename rdr3 +set sv_enforceGameBuild 1436 +sets sv_projectName "${SERVER_NAME}" +sets sv_projectDesc "${SERVER_DESC}"'
      LICENSE_KEY: ${LICENSE_KEY}
      NO_LICENSE_KEY: ${NO_LICENSE_KEY}
      NO_ONESYNC: ${NO_ONESYNC}
      RCON_PASSWORD: ${RCON_PASSWORD}
      STEAM_API_KEY: ${STEAM_API_KEY}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  mysql:
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './mysql:/var/lib/mysql'
      - './sql:/docker-entrypoint-initdb.d'
    networks:
      - fivem
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      
networks:
    fivem:
        driver: bridge
