#version: '3'

services:
  fivem:
    build:
      context: ./docker
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "./resources:/config/resources"
      - "./server.cfg:/root/server.cfg"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
    environment:
      CONFIG_ARGS: "+set gamename rdr3"
      LICENSE_KEY: ${LICENSE_KEY}
      NO_LICENSE_KEY: ${NO_LICENSE_KEY}
      RCON_PASSWORD: ${RCON_PASSWORD}
      STEAM_API_KEY: ${STEAM_API_KEY}
