name: Build

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Clone repository
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
