name: Build

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Clone repository
        uses: actions/checkout@v2
      -
        name: Build Image
        run: docker-compose build
      -
        name: Create .env
        run: cp .env.example .env && echo "NO_LICENSE_KEY=true" >> .env && sed -i "s/RCONPassword/password/g" .env && sed -i "s/SteamAPIKey/${{ secrets.STEAM_API_KEY }}/g" .env
      - 
        name: Run the image
        run: docker-compose up -d
      - 
        name: Log the container
        run: docker-compose logs
      - 
        name: List server-data files
        run: ls -la /output/opt/cfx-server-data
      -
        name: Stop the container
        run: docker-compose down
