name: ExtractSQL

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Extract SQL
        run: ./maintenance/extract-sql.sh
      -
        name: Commit the changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'GitHub Action'
            git config --global user.email 'noreply@github.com'
            git add .
            git commit -am "Extracted SQL"
            git push
          else
            echo "No changes, skipping."
          fi
