name: Publish

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Clone repository
        uses: actions/checkout@v2
      -
        name: Increase build number
        run: |
          export $(cat .env.example | sed 's/#.*//g' | xargs)
          
          mkdir -p .github/buildno
          
          find .github/buildno ! -name "$FIVEM_NUM" -type f -exec rm -f {} +
          
          if -f ".github/buildno/$FIVEM_NUM"; then
            export OLD_BUILD_NUMBER=`cut -d ',' -f2 .github/buildno/$FIVEM_NUM`  
            NEW_BUILD_NUMBER=`expr $OLD_BUILD_NUMBER + 1`
            sed -i "s/$OLD_BUILD_NUMBER\$/$NEW_BUILD_NUMBER/g" .github/buildno/$FIVEM_NUM
          else
            echo "0" > .github/buildno/$FIVEM_NUM
          fi
          
          echo "fivem_build=$FIVEM_NUM" >> $GITHUB_ENV
          echo "build_number=$(cat .github/buildno/$FIVEM_NUM)" >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/fivem
          file: docker/fivem/Dockerfile
          push: true
          tags: |
            skyraptor/fivem:latest
            skyraptor/fivem:${{ env.fivem_build }}
            skyraptor/fivem:${{ env.fivem_build }}-${{ env.build_number }}
      -
        name: Tag and push
        runs: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'noreply@github.com'
          
          git tag ${{ env.fivem_build }}-${{ env.build_number }}
          
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -am "Successfully built image"
            git push
          fi
          
          git push --tags
