name: UpdateFiveM

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Install RSM
        run: sudo ./install-rsm.sh
      -
        name: Get & update FiveM
        run: |
          OUTPUT=$(rsm build-info)
          echo "Received build info:  \"$OUTPUT\""
          BUILD=$(echo $OUTPUT | grep -oP '(?<=Build: \")[^\"]*')
          echo "Extracted build:  \"$BUILD\""
          COMMIT=$(echo $OUTPUT | grep -oP '(?<=Commit: \")[^\"]*')
          echo "Extracted commit:  \"$COMMIT\""
          sed -i "s/FIVEM_NUM=.*/FIVEM_NUM=$BUILD/" .env.example
          sed -i "s/FIVEM_VER=.*/FIVEM_VER=$COMMIT/" .env.example
          sed -i "s/ARG FIVEM_NUM=.*/ARG FIVEM_NUM=$BUILD/" docker/fivem/Dockerfile
          sed -i "s/ARG FIVEM_VER=.*/ARG FIVEM_VER=$COMMIT/" docker/fivem/Dockerfile
      -
        name: Get & update CitizenX data
        run: |
          OUTPUT=$(git ls-remote https://github.com/citizenfx/cfx-server-data.git HEAD)
          COMMIT=$(echo $OUTPUT | grep -oP '(^[\w]*)')
          sed -i "s/ARG DATA_VER=.*/ARG DATA_VER=$COMMIT/" docker/Dockerfile
      -
        name: Commit the changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'GitHub Action'
            git config --global user.email 'noreply@github.com'
            git add .
            git commit -am "Updated FiveM Build & Data"
            git push
          else
            echo "No changes, skipping."
          fi
